---
production: &default
  serverPort: 3000
  baseUrl: http://www.studiovictory.com
  baseApi: /api/
  views:
    engine: .hbs
    extension: .hbs
    layout: main
  html:
    minify: true
    css:
      stylusPrecompile: true
      compress: true
  controllers:
    default: home
  languages:
    default: en
    list: [en, es, fr, pt, jp]

stage: &stage
  <<: *default
  baseUrl: http://stage.studiovictory.com

latest: &latest
  <<: *stage
  baseUrl: http://latest.studiovictory.com

development:
  <<: *latest
  baseUrl: http://local.studiovictory.com
  html:
    minify: false
    css:
      stylusPrecompile: false
      compress: false
